name: Publish release to npm
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    env: 
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    defaults:
      run:
        working-directory: library
    steps:
      - uses: actions/checkout@v2
      - name: Set env RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: "https://registry.npmjs.org"
      - run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run build
      - run: npm --allow-same-version --no-git-tag-version version "${{ env.RELEASE_VERSION }}"
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./library/package.json
          token: ${{ secrets.NPM_TOKEN }}
          access: private
          tag: latest
          check-version: false
